import React,{useState}from'react';import{useAuth}from'../contexts/AuthContext';import{Button}from'../components/ui/button';import{Input}from'../components/ui/input';import{Card,CardContent,CardHeader,CardTitle}from'../components/ui/card';import{toast}from'sonner';import{Activity,AlertTriangle,BarChart3,Bell,CalendarCheck,ClipboardCheck,FileBarChart,Gauge,History,LayoutDashboard,LogOut,Menu,Package,Plus,Search,Settings,ShieldCheck,Snowflake,Truck,Wrench,X}from'lucide-react';
const menus=[['painel','Painel principal',LayoutDashboard],['equipamentos','Equipamentos',Snowflake],['frota','Frota',Truck],['os','Ordens de serviço',Wrench],['preventivas','Preventivas',CalendarCheck],['inspecoes','Inspeções',ClipboardCheck],['relatorios','Relatórios',FileBarChart],['historico','Histórico técnico',History],['administracao','Administração',Settings]];
const orders=[['OS-2026-00142','Oscilação de temperatura na câmara 03','Câmaras frias','Refrigeração','Crítica','Em andamento','Carlos Mendes','2h 18min'],['OS-2026-00141','Substituição da lâmina da serra de carcaça','Sala de abate','Mecânica','Alta','Aguardando material','João Silva','5h 42min'],['OS-2026-00139','Revisão elétrica do caminhão refrigerado','Frota','Frota','Média','Aberta','Atribuir mecânico','1h 05min'],['OS-2026-00138','Vazamento no pistão pneumático da linha 02','Desossa','Pneumática','Urgente','Em andamento','Marcos Souza','1 dia']];
const assets=[['EQ-0018','Compressor Schulz 40HP','Sala de máquinas','Crítica','Operando normal'],['EQ-0032','Serra de carcaça Jarvis','Sala de abate','Alta','Em manutenção'],['EQ-0047','Câmara fria 03','Câmaras frias','Crítica','Em observação'],['EQ-0075','Pistão pneumático linha 02','Desossa','Média','Parado']];const fleet=[['F-012','QWE-4A21','Caminhão refrigerado','Mercedes-Benz Atego','Em manutenção','184.230 km'],['F-018','RTY-9B03','Caminhão refrigerado','Volkswagen Delivery','Operando','92.110 km'],['F-025','ASD-2C91','Caçamba','Ford Cargo','Liberado','221.450 km']];
const metrics=[['OS abertas','12',Wrench,'red'],['Em andamento','7',Activity,'amber'],['Finalizadas hoje','9',ShieldCheck,'green'],['OS atrasadas','3',AlertTriangle,'red'],['Preventivas do dia','6',CalendarCheck,'blue'],['Equipamentos parados','2',Package,'red'],['Veículos parados','1',Truck,'amber'],['Demandas urgentes','4',Bell,'red']];const tone=v=>v.includes('normal')||v==='Operando'||v==='Liberado'?'green':v==='Aberta'?'blue':v.includes('andamento')||v.includes('manutenção')||v.includes('material')||v.includes('observação')?'amber':'red';
const Badge=({children,color='gray'})=><span className={'badge '+color}>{children}</span>;const Table=({children})=><div className="table-wrap"><table>{children}</table></div>;
function QuickOS({close}){return <div className="backdrop"><Card className="modal"><CardHeader><button onClick={close}><X/></button><p className="eyebrow">Abertura rápida</p><CardTitle>Nova ordem de serviço</CardTitle></CardHeader><CardContent><div className="form">{['Origem','Setor','Equipamento ou veículo','Tipo da OS','Prioridade'].map(x=><label>{x}<select><option>Selecione</option><option>Equipamento</option><option>Veículo</option></select></label>)}<label className="wide">Descrição da demanda<textarea placeholder="Descreva objetivamente o problema encontrado"/></label></div><Button className="primary full" onClick={()=>{close();toast.success('OS aberta com sucesso.')}}>Salvar ordem de serviço</Button></CardContent></Card></div>}
export const Maintenance=()=>{const{user,logout}=useAuth();const[page,setPage]=useState('painel'),[mobile,setMobile]=useState(false),[quick,setQuick]=useState(false),[query,setQuery]=useState('');const title=menus.find(x=>x[0]===page)[1];const Sidebar=()=> <aside className={'sidebar '+(mobile?'open':'')}><div className="brand"><div className="mark"><Snowflake/></div><div><b>Campo do Gado</b><small>Manutenção Frigorífico</small></div><button onClick={()=>setMobile(false)}><X/></button></div><nav>{menus.map(([id,label,I])=><button className={id===page?'active':''} onClick={()=>{setPage(id);setMobile(false)}}><I/>{label}</button>)}</nav><footer><span>{user?.nome?.slice(0,2).toUpperCase()||'CG'}</span><div><b>{user?.nome||'Administrador'}</b><small>{user?.role||'admin'}</small></div><button onClick={logout}><LogOut/></button></footer></aside>;
const Actions=({asset=false})=><section className="actions"><div><Search/><Input placeholder={asset?'Buscar equipamento':'Buscar por OS, ativo ou setor'} value={query} onChange={e=>setQuery(e.target.value)}/></div><Button className="primary" onClick={()=>setQuick(true)}><Plus/> {asset?'Novo equipamento':'Nova OS'}</Button></section>;
const Dashboard=()=> <><section className="welcome"><div><p>VISÃO GERAL DA OPERAÇÃO</p><h2>Bom dia, {user?.nome?.split(' ')[0]||'equipe'}!</h2><span>Acompanhe as prioridades da manutenção do frigorífico em tempo real.</span></div><Button onClick={()=>setQuick(true)}><Plus/> Nova OS</Button></section><section className="metrics">{metrics.map(([a,b,I,c])=><Card><CardContent><i className={c}><I/></i><div><b>{b}</b><span>{a}</span></div></CardContent></Card>)}</section><div className="columns"><Card><CardHeader><CardTitle>Ordens prioritárias</CardTitle></CardHeader><CardContent>{orders.slice(0,3).map(o=><article><div><b>{o[0]}</b><h3>{o[1]}</h3><p>{o[2]} • {o[6]}</p></div><aside><Badge color={o[4]==='Crítica'?'red':'amber'}>{o[4]}</Badge><Badge color={tone(o[5])}>{o[5]}</Badge></aside></article>)}</CardContent></Card><Card><CardHeader><CardTitle>Preventivas de hoje</CardTitle></CardHeader><CardContent><Progress name="Inspeção de câmaras frias" value="75%"/><Progress name="Verificação da frota refrigerada" value="33%"/><div className="warning"><AlertTriangle/>2 preventivas atrasadas aguardando execução.</div></CardContent></Card></div></>;
const Progress=({name,value})=><div className="progress"><b>{name}</b><small>{value} concluído</small><i><em style={{width:value}}/></i></div>;
const Orders=()=> <><Actions/><Card><CardContent><Table><thead><tr>{['OS / Demanda','Setor','Categoria','Prioridade','Status','Responsável','Tempo'].map(x=><th>{x}</th>)}</tr></thead><tbody>{orders.filter(o=>(o.join(' ')).toLowerCase().includes(query.toLowerCase())).map(o=><tr><td><b>{o[0]}</b><small>{o[1]}</small></td><td>{o[2]}</td><td>{o[3]}</td><td><Badge color={o[4]==='Crítica'?'red':'amber'}>{o[4]}</Badge></td><td><Badge color={tone(o[5])}>{o[5]}</Badge></td><td>{o[6]}</td><td>{o[7]}</td></tr>)}</tbody></Table></CardContent></Card></>;
const Assets=()=> <><Actions asset/><Card><CardContent><Table><thead><tr>{['Código','Equipamento','Setor','Criticidade','Situação atual',''].map(x=><th>{x}</th>)}</tr></thead><tbody>{assets.map(a=><tr>{a.slice(0,3).map(x=><td>{x}</td>)}<td><Badge color={a[3]==='Crítica'?'red':'amber'}>{a[3]}</Badge></td><td><Badge color={tone(a[4])}>{a[4]}</Badge></td><td><button className="link">Ver histórico</button></td></tr>)}</tbody></Table></CardContent></Card></>;
const Fleet=()=> <><Actions/><div className="fleet">{fleet.map(v=><Card><CardContent><header><Truck/><Badge color={tone(v[4])}>{v[4]}</Badge></header><h3>{v[0]} • {v[1]}</h3><p>{v[2]}</p><b>{v[3]}</b><footer><span><Gauge/>{v[5]}</span><button>Ver histórico</button></footer></CardContent></Card>)}</div></>;
const Generic=()=> <div className="modules">{[['Operação organizada','Fluxos preparados para uso diário.',ClipboardCheck],['Rastreabilidade completa','Responsável, perfil, data e hora em cada ação.',History],['Filtros e relatórios','Consultas técnicas e PDFs institucionais.',BarChart3]].map(([a,b,I])=><Card><CardContent><I/><h3>{a}</h3><p>{b}</p><Button className="primary">Acessar recurso</Button></CardContent></Card>)}</div>;
return <div className="shell"><Sidebar/><main><header className="top"><button onClick={()=>setMobile(true)}><Menu/></button><div><p>MANUTENÇÃO INDUSTRIAL • FRIGORÍFICO + FROTA</p><h1>{title}</h1><span>Controle simples, rápido e preparado para celular.</span></div><Bell/></header><div className="content">{page==='painel'?<Dashboard/>:page==='os'?<Orders/>:page==='equipamentos'?<Assets/>:page==='frota'?<Fleet/>:<Generic/>}</div></main>{quick&&<QuickOS close={()=>setQuick(false)}/>}</div>}
